name: build-raspberry

on:
#  push:
#    branches: [ dev ]
#  pull_request:
#    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Update system
        run: |
          sudo apt update
          sudo apt upgrade -y
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: true
          path: photobooth
      - name: Checkout pi-gen
        uses: actions/checkout@v3
        with:
          repository: RPI-Distro/pi-gen
          path: pi-gen
      - name: Install pi-gen dependencies
        run: |
          #git clone --depth 1 https://github.com/RPI-Distro/pi-gen.git
          cat pi-gen/depends | rev | cut -d: -f1 | rev | xargs sudo apt install -y
      - name: Run pi-gen
        run: |
          export IMG_NAME=photobooth-pi
          export RELEASE=buster
          export DEPLOY_ZIP=1
          export LOCALE_DEFAULT=en_US.UTF-8
          export TARGET_HOSTNAME=photobooth-pi
          export KEYBOARD_KEYMAP=us
          export KEYBOARD_LAYOUT="English (US)"
          export TIMEZONE_DEFAULT=America/New_York
          export FIRST_USER_NAME=photobooth
          export FIRST_USER_PASS=photobooth
          export ENABLE_SSH=1
          
          chmod +x pi-gen/build.sh
          pi-gen/build.sh
      - name: Last Job
        run: |
          pwd
          ls -la
          ls -la pi-gen
          ls -la photobooth
#      - name: Compress
#        run: |
#          cd vendor/CustomUbuntu/scripts
#          gzip photobooth.iso
#      - name: Publish ISO
#        uses: actions/upload-artifact@v2
#        with:
#          name: photobooth.iso.gz
#          path: vendor/CustomUbuntu/scripts/photobooth.iso.gz
#      - name: deploy file
#        uses: wlixcc/SFTP-Deploy-Action@v1.0
#        with:
#          username: ${{ secrets.SSH_USER }} 
#          server: ${{ secrets.SSH_SERVER }} 
#          ssh_private_key: ${{ secrets.SSH_KEY }} 
#          local_path: 'vendor/CustomUbuntu/scripts/photobooth.iso.gz'
#          remote_path: './'
#          args: '-o ConnectTimeout=5'
#      - name: Release
#        uses: softprops/action-gh-release@v1
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        with:
#          tag_name: focal-latest
#          prerelease: true
#          files: |
#            scripts/ubuntu-from-scratch.iso.gz
