name: Build

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install modules
        run: yarn install
      - name: Build
        run: yarn build
      - name: Get git status
        run: git status
      - name: Pack zip
        run: yarn pack:build
      - name: Publish zip
        uses: actions/upload-artifact@v2
        if: github.actor != 'dependabot[bot]' && github.actor != 'dependabot-preview[bot]'
        with:
          name: photobooth
          path: archives/photobooth-*.zip
  buildmacos:
    runs-on: macos-11
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install modules
        run: yarn install
      - name: Build
        run: yarn build
